os: linux
language: generic
services:
- docker
env:
  global:
  - DOCKER_TAG="zfs-archiso-build"
  - ISO_REL="zfs-archiso-$(date +%Y-%m-%d)"
  - BUILD_DIR="/opt/zfs-archiso"
  - PUBLISHER="eurgghh"
  - RELEASE_ISO="$(find ./out -name '*.iso')"
before_script:
  - docker build -t "$DOCKER_TAG" .
script:
  - docker run --privileged --volume="$PWD/out:/opt/zfs-archiso/out" "$DOCKER_TAG"
before_deploy:
  - mv $PWD/out/*.iso $PWD/out/"${ISO_PREFIX}-${ISO_VER}"-x86_64.iso
  - git config --local user.name "$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - git config --local user.email "$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
  - git tag "$ISO_REL"
  - export 
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  overwrite: true
  file: "$RELEASE_ISO"
  on:
    repo: "$PUBLISHER/zfs-archiso"
notifications:
  email: false
